# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "wheezy64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-puppet.box"
  config.vm.network :private_network, :ip => "192.168.33.10"
  config.vm.hostname = "arroyo"
  config.ssh.forward_agent = true
  config.vm.synced_folder "../www", "/var/www", type: "nfs"
  config.vm.synced_folder "../shared", "/home/vagrant/shared", type: "nfs"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.librarian_puppet.puppetfile_dir = "puppet/forge"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file  = "init.pp"
    puppet.module_path = ["puppet/forge/modules", "puppet/custom/modules"]
  end
end
